"""add whatsapp manual connect

Revision ID: 83c501959c41
Revises: f200c34208f8
Create Date: 2026-03-05 02:56:56.011720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c501959c41'
down_revision: Union[str, None] = 'f200c34208f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('whatsapp_phone_number_id', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('whatsapp_access_token', sa.Text(), nullable=True))
    op.add_column(
    'businesses',
    sa.Column(
        'whatsapp_connected',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    op.drop_constraint('businesses_phone_number_id_key', 'businesses', type_='unique')
    op.create_unique_constraint(None, 'businesses', ['whatsapp_phone_number_id'])
    op.drop_column('businesses', 'waba_id')
    op.drop_column('businesses', 'access_token')
    op.drop_column('businesses', 'phone_number_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('phone_number_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('waba_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'businesses', type_='unique')
    op.create_unique_constraint('businesses_phone_number_id_key', 'businesses', ['phone_number_id'])
    op.drop_column('businesses', 'whatsapp_connected')
    op.drop_column('businesses', 'whatsapp_access_token')
    op.drop_column('businesses', 'whatsapp_phone_number_id')
    # ### end Alembic commands ###
